# Generated by Django 5.0.2 on 2024-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_maintainer',
            field=models.BooleanField(default=False),
        ),
    ]
