# Generated by Django 5.0.2 on 2024-04-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_orderitem_is_delivered_orderitem_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
