# Generated by Django 5.0.2 on 2024-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_order_delivery_address_orderitem_delivered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
